### ISSUE TITLE
Move to pixi.js org? :)

### ISSUE THREAD

**Issue by ivanpopelyshev** [avgjs/pixi-live2d#1]
Hey there! I'm maintainer of [pixi-spine](https://github.com/pixijs/pixi-spine)

I propose to move the repo to pixi.js org, making it official. I also offer help with maintaining it. Btw, I had a prototype of shader for that kind of animations.

You can create an issue in https://github.com/pixijs/pixi.js/issues and we figure out what to do with that.

I understand how live2d is important when you want to make a japanese novel game, and I'll help other people with setting up to make new games of that kind. Also, your plugin is hope for all people in [rpgmakerMV](rpgmakerweb.com)

**Comment by Icemic** [comment]
That's good! 

In fact, I just joined a independent game team using RMMV!

And this **AVG.js Project** is a AVG Development Framework(or say ENGINE?) based on pixi.js, which will be open-sourced soon!

**Comment by ivanpopelyshev** [comment]
Nice! You can pester me about graphical parts of RMMV :)
