### ISSUE TITLE
I stopped by... and I was completely AMAZED!

### ISSUE THREAD

**Issue by inglesuniversal** [avgjs/pixi-live2d#10]
Congratulations for this AMAZING Project!

I hope I can learn to use this tool.

Regards

**Comment by linonetwo** [comment]
I think using this project doesn't means you can use live2d for free, I guess?

**Comment by Icemic** [comment]
> I think using this project doesn't means you can use live2d for free, I guess?

Apparently not, you must pay for a license to Live2D company.

> Congratulations for this AMAZING Project!
> 
> I hope I can learn to use this tool.
> 
> Regards

Thx  :p

**Comment by inglesuniversal** [comment]
Out of curiosity... I checked the license of this project and it appears as MIT... but even so, I would greatly consider supporting the authors with Donations and bonuses for their hard work pulling this together... I think the only drawback at this time, is lack of manuals or support since it was created in a foreign language (Japanese) I guess. Good luck fellas!
