### ISSUE TITLE
貌似年久失修了...?

### ISSUE THREAD

**Issue by RERASER** [avgjs/pixi-live2d#12]
![image](https://user-images.githubusercontent.com/63722060/150649358-dec741e3-c64b-4595-9b21-8e72f7285703.png)
Readme中的下载已不可用,我尝试使用了live2dcubismcore.min.js进行替代,然后得到了这个错误
![image](https://user-images.githubusercontent.com/63722060/150649443-e293f380-00d3-46b5-8761-16549cc04fb5.png)

**Comment by Icemic** [comment]
@RERASER 大部分的需求现在应该能使用 pixijs 官方的另一个支持库。因为live2d官方已经多次迭代，不确定与最新版本的兼容性。

**Comment by try-to-fly** [comment]
https://github.com/guansss/pixi-live2d-display/
