### ISSUE TITLE
Use glCore instead of "gl.XXX" operations

### ISSUE THREAD

**Issue by ivanpopelyshev** [avgjs/pixi-live2d#2]
Currently plugin bypasses PIXI.glCore and directly uses webgl stuff. We can port it that way code will look much better.

Also with upcoming https://github.com/pixijs/pixi.js/tree/dev-geometry , it'll be even easier to add ingame

**Comment by Icemic** [comment]
I'm not sure how to use PIXI.glCore, does it has some docs?

And, what's the features of `dev-geometry` branch?

**Comment by Icemic** [comment]
Is it the project `The big geometry conversion`?

Once I need `crossfade` or `dynamic-mask` transition, but it seems that pixi.js doesn't have this function yet, so I have to add a 'hacking filter' to sprite.filters, and use it as a proxy to implement it :(

If it can bring more freedom for shader, i think it could not be better!
