### ISSUE TITLE
all version have error '_live2d.Live2D.setGL is not a function'

### ISSUE THREAD

**Issue by mike-hor** [avgjs/pixi-live2d#7]
![image](https://user-images.githubusercontent.com/17822235/29807279-d676d18c-8cc5-11e7-8d38-eb058290fd14.png)
such as this,i try all ways ,but can not import package.(error, .sprite no define)
i just direct reference pixi-live2d@1.2.1,have error '_live2d.Live2D.setGL is not a function' too!!!

**Comment by Icemic** [comment]
Hi, sorry for the late.

It's seems that the live2d sdk doesn't exist? 

Because of the SDK policy of Live2D Inc., SDK file has been removed from the package, so you have to download and import it by yourself.

See more in readme file
